# Generated by Django 5.0.2 on 2024-04-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='password_length',
            field=models.PositiveIntegerField(default=8),
            preserve_default=False,
        ),
    ]
