# Generated by Django 5.0.2 on 2024-04-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass_gen', '0003_remove_password_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_length',
            field=models.PositiveIntegerField(),
        ),
    ]
