# Generated by Django 5.0.2 on 2024-04-20 19:54

import Pass_gen.validator
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pass_gen', '0005_alter_password_password_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_length',
            field=Pass_gen.validator.UnsignedNonZeroIntegerField(validators=[Pass_gen.validator.validate_non_zero]),
        ),
    ]
