# Generated by Django 5.0.2 on 2024-04-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass_gen', '0006_alter_password_password_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_length',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
