# Generated by Django 5.0.2 on 2024-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass_gen', '0007_alter_password_password_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='password',
            field=models.CharField(default=1111, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='password_length',
            field=models.PositiveIntegerField(),
        ),
    ]
